name:  build and test
on:  [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name:  show folder content
        run:  ls -l
      - uses: actions/checkout@v4
        name:  Git checkout
      - name:  show folder content
        run:  ls -l
      - name:  build
        run:  dotnet build

  test:
    runs-on: ubuntu-latest
    needs:  [build]
    steps:
      - uses: actions/checkout@v4
        name:  Git checkout
      - name:  test
        run:  dotnet test
    