name:  build and test
on:  [push]
jobs:
  git_code:
    runs-on: ubuntu-latest
    steps:
      - name:  show folder content
        run:  ls -l
      - uses: actions/checkout@v4
        name:  Git checkout
      - name:  show folder content
        run:  ls -l

  #build:
    