name:  contexts
on:
  push:
    paths:
      - "**contexts.yaml"
jobs:
  show_contexts:
    runs-on: ubuntu-latest
    steps:
      - name:  show contexts
        run:  |
            echo "github: ${{toJson(github)}}}"
            echo "secrets: ${{toJson(secrets)}}"
            echo "job: ${{toJson(job)}}"
            echo "runner: ${{toJson(runner)}}"