name:  dependent jobs 2
on:  [push]
jobs:
  fake_build:
    runs-on: ubuntu-latest
    steps:
      - run:  |
          echo "Fake build"
          sleep 10
          exit 1
        name:  Fake build

  fake_test:
    runs-on: ubuntu-latest
    needs:  fake_build
    steps:
      - run:  |
          echo "Fake test"
          sleep 10
        name:  Fake test

  report_on_failure:
    runs-on: ubuntu-latest
    needs:  [fake_build]
    if:  failure()
    steps:
      - run:  |
          echo "Report on failure"
          sleep 10
        name:  Report on failure