name:  first test
on:  [workflow_dispatch, push, pull_request, issues]
jobs:  
  first_hello_mumm:
    runs-on: ubuntu-latest
    steps:
      - run:  echo "Hello Mumm"
        name:  Hello Mumm
  
  second_hello_test:
    runs-on: ubuntu-latest
    steps:
      - run:  curl -s https://www.google.com
        name:  curl google

  third_hello_test:
    runs-on: ubuntu-latest
    steps:
      - run:  exit 1
        name:  exit fail