name:  first test
on:  [workflow_dispatch]
jobs:  
  first_hello_mumm:
    runs-on: ubuntu-latest
    steps:
      - run:  |
          echo "Hello Mumm"
          sleep 10
        name:  Hello Mumm
  
  second_hello_test:
    runs-on: ubuntu-latest
    steps:
      - run:  curl -s https://www.google.com
        name:  curl google

  third_hello_test:
    runs-on: ubuntu-latest
    steps:
      - run:  exit 1
        name:  exit fail

  fourth_hello_test:
    runs-on: ubuntu-latest
    steps:
      - run:  |
          echo "4th run"
          sleep 13
        name:  fourth run