name:  logic output
on:  [push, workflow_dispatch]
jobs:
  hello_world:
    runs-on: ubuntu-latest
    steps:
      - run:  |
          echo "Hello World"
          sleep 10
        name:  Hello World

  show_logic_output:
    runs-on: ubuntu-latest
    steps:
      - name:  show logic output
        run:  |
            echo ${{1}}
            echo ${{null}}
            echo "4=3 ${{4==3}}"
            echo "4!=3 ${{4!=3}}"
            echo "4>3 ${{4>3}}"
            echo "4<3 ${{4<3}}"

  conditional_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name:  Git checkout
      - name:  conditional build
        run:  |
            dotnet build
    if:  ${{github.event_name == 'push'}}
