name:  multirun 
on:  [push]
jobs:  
  build_and_test:
    strategy:
      matrix:
        os:  [ubuntu-latest, windows-latest]
    runs-on:  ${{matrix.os}}
    steps:
      - name:  show folder content
        run:  ls -l
      - uses: actions/checkout@v4
        name:  Git checkout
      - name:  show folder content
        run:  ls -l
      - name:  build
        run:  dotnet build
      - name:  test
        run:  dotnet test