name:  node build
on:  [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name:  show folder content
        run:  ls -l
      - uses: actions/checkout@v4
        name:  Git checkout
      - name:  use cache for node packages
        uses: actions/cache@v4
        with: 
          path:  nodejs/node_modules
          key:  our_modules
        id:  cache_modules
      - name:  show folder content
        run:  ls -l
      - name:  pull modules
        run:  |
            cd nodejs
            npm install
      - name:  check_cache
        run:  echo "Cache hit ${{toJson(steps.cache_modules.outputs)}}"
        # contains(steps.cache_modules.outputs.cache-hit, 'true')