name:  using vars 2
on:  [push]
jobs:
  show_vars:
    runs-on: ubuntu-latest
    environment:  production
    steps:
      - name:  show vars
        run:  |
            echo "vars: ${{vars.MY_ENVIRONMENT_VARIABLE_1}}"